# Generated by Django 4.1.2 on 2022-10-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSample', '0002_alter_hnguser_bio_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
